### PR TITLE
BUG: ENH: update spa_files to patch timezone bug

### LINKED ISSUE #168: spa_c_files don't build with VC14 (Python 3.5)
windows 7 amd64
Cython (0.24)
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32

if I try to build spa_c for Python-3.5 I get the following:

```
$ py -3.5 setup.py build_ext --inplace
running build_ext
building 'spa_py' extension
creating build
creating build\temp.win-amd64-3.5
creating build\temp.win-amd64-3.5\Release
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Python35\include -IC:\Python35\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /Tcspa_py.c /Fobuild\temp.win-amd64-3.5\Release\spa_py.obj
spa_py.c
c:\users\mmikofski\documents\projects\pvlib-python\pvlib\spa_c_files\spa.h(88): error C2032: '__timezone': function cannot be member of struct '<unnamed-tag>'
spa_py.c(854): error C2059: syntax error: '('
spa_py.c(1700): error C2059: syntax error: '('
spa_py.c(1702): error C2275: 'PyObject': illegal use of this type as an expression
c:\python35\include\object.h(110): note: see declaration of 'PyObject'
spa_py.c(1702): error C2059: syntax error: ')'
spa_py.c(1702): error C2223: left of '->ob_refcnt' must point to struct/union
spa_py.c(1702): error C2065: '_py_decref_tmp': undeclared identifier
spa_py.c(1702): warning C4312: 'type cast': conversion from 'int' to 'PyObject *' of greater size
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2
```

### PR DESCRIPTION
**Pull request by mikofski**
* closes #168
* get source and header in `setup.py`
* replace "timezone" with "timezone" to fix the bug
* also update readme
* also remove a lot of extra whitespace and tabs

Signed-off-by: Mark Mikofski <bwana.marko@yahoo.com>

### CODE REVIEW

File: pvlib/spa_c_files/README.md [hunk 1]
```diff
@@ -1,34 +1,38 @@
...
 
-** Due to licensing issues, you must download the NREL C files from their 
-[website](http://www.nrel.gov/midc/spa) **
-
-Download the ``spa.c`` and ``spa.h`` files from NREL, 
-and copy them into the ``pvlib/spa_c_files`` directory. 
+** Due to licensing issues, the [SPA C files](http://www.nrel.gov/midc/spa) can
+_not_ be included in the pvlib-python distribution. The SPA C files will be
+downloaded when you build the Python extension. By using this module you agree
+to the NREL license in SPA_NOTICE. **
```
Comment (wholmgren) [inline pvlib/spa_c_files/README.md]: I'm concerned about adding this feature. Can we really say this and wash our hands of the license issue? I would be surprised. I'd believe we're in the clear if we pulled the license text, printed it, and waited for the user to input ``y``.

Also not clear to me how this is supposed to work (or not work) with the spa related code in the root setup.py

Comment (wholmgren) [reply pvlib/spa_c_files/README.md]: (by this feature I mean the auto-download capability)

File: pvlib/spa_c_files/README.md [hunk 2]
```diff
@@ -1,34 +1,81 @@
...
 This folder contains the files required to make NREL's C code accessible
 to the ``pvlib-python`` package. We use the Cython package to wrap NREL's SPA 
 implementation. 
 
-** Due to licensing issues, you must download the NREL C files from their 
-[website](http://www.nrel.gov/midc/spa) **
-
-Download the ``spa.c`` and ``spa.h`` files from NREL, 
-and copy them into the ``pvlib/spa_c_files`` directory. 
+** Due to licensing issues, the [SPA C files](http://www.nrel.gov/midc/spa) can
```
Comment (wholmgren) [inline pvlib/spa_c_files/README.md]: http://www.nrel.gov/midc/spa forwards to https://midcdmz.nrel.gov/

looks like https://midcdmz.nrel.gov/spa/ is now the correct url

File: pvlib/spa_c_files/README.md (hunk 1 above)
Comment (mikofski) [reply pvlib/spa_c_files/README.md]: > I'm concerned about adding this feature. Can we really say this and wash our hands of the license issue? I would be surprised.

but the LICENSED code is not being distributed with pvlib, so I don't see the concern?

>I'd believe we're in the clear if we pulled the license text, printed it, and waited for the user to input `y`.

I guess we can do that

>Also not clear to me how this is supposed to work (or not work) with the spa related code in the root `setup.py`

AFAIK there's no difference, everything is exactly the same way it was before. The user has to follow the instructions in the README. If they want to use the SPA C-files, then they need to somehow enter this folder and run

    python setup.py build_ext --inplace

it's the only way to build it, and by doing this act, then implicitly agree to the license. If they don't want to use the SPA C-files they do nothing. AFAIK the rest of pvlib still works exactly the way it always did, what's different?

Comment (wholmgren) [reply pvlib/spa_c_files/README.md]: >but the LICENSED code is not being distributed with pvlib, so I don't see the concern?

Maybe. But I don't want NREL to think "Holmgren, Mikofski, and the rest of those ^&*( pvlib-ers snaked their way around our license."

If we support automatic download, I'd also want a user to be required to input the form information rather than it being supplied as "pvlib-python" etc. NREL is presumably asking for this information from each user in order to justify funding to DOE. Putting a placeholder there doesn't seem right, regardless of whether we agree with NREL's strategy here or not. 

>AFAIK there's no difference, everything is exactly the same way it was before.

The root setup.py compiles the extension if the files were detected during a ``pip install .`` or ``python setup.py``. Or at least it used to -- it's been years since I tried. Perhaps it's best to remove the capability of the root setup.py to do anything with this extension.

**Comment by mikofski** [comment]
okay, the user is forced to see the license and push a key to install now, here's what they see:

```
>python setup.py build_ext --inplace
# NOTICE

Copyright (c) 2008-2011 Alliance for Sustainable Energy, LLC, All Rights Reserved

The Solar Position Algorithm ("Software") is code in development prepared by
employees of the Alliance for Sustainable Energy, LLC, (hereinafter the
"Contractor"), under Contract No. DE-AC36-08GO28308 ("Contract") with the
U.S. Department of Energy (the "DOE"). The United States Government has been
granted for itself and others acting on its behalf a paid-up, non-exclusive,
irrevocable, worldwide license in the Software to reproduce, prepare
derivative works, and perform publicly and display publicly. Beginning five
(5) years after the date permission to assert copyright is obtained from the
DOE, and subject to any subsequent five (5) year renewals, the United States
Government is granted for itself and others acting on its behalf a paid-up,
non-exclusive, irrevocable, worldwide license in the Software to reproduce,
prepare derivative works, distribute copies to the public, perform publicly
and display publicly, and to permit others to do so. If the Contractor ceases
to make this computer software available, it may be obtained from DOE's
Office of Scientific and Technical Information's Energy Science and
Technology Software Center (ESTSC) at P.O. Box 1020, Oak Ridge, TN
37831-1020. THIS SOFTWARE IS PROVIDED BY THE CONTRACTOR "AS IS" AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE CONTRACTOR OR THE U.S. GOVERNMENT BE LIABLE
FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER,
INCLUDING BUT NOT LIMITED TO CLAIMS ASSOCIATED WITH THE LOSS OF DATA OR
PROFITS, WHICH MAY RESULT FROM AN ACTION IN CONTRACT, NEGLIGENCE OR OTHER
TORTIOUS CLAIM THAT ARISES OUT OF OR IN CONNECTION WITH THE ACCESS, USE OR
PERFORMANCE OF THIS SOFTWARE.

The Software is being provided for internal, noncommercial purposes only and
shall not be re-distributed. Please contact [Jean
Schulte](mailto:Jean.Schulte@nrel.gov) in the NREL Commercialization and
Technology Transfer Office for information concerning a commercial license to
use the Software.

As a condition of using the Software in an application, the developer of the
application agrees to reference the use of the Software and make this Notice
readily accessible to any end-user in a Help|About screen or equivalent manner.

By continuing you accept the NREL LICENSE. Press any key ...
```

Then they have to press a key to continue.

```
running build_ext
building 'spa_py' extension
<some compiler stuff>
spa_py.c
<more compiler stuff>
spa.c
spa.c(535): warning C4244: 'return': conversion from 'double' to 'int', possible loss of data
spa.c(1072): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
<even more compiler stuff>
   Creating library build\temp.win-amd64-3.7\Release\spa_py.cp37-win_amd64.lib and object build\temp.win-amd64-3.7\Release\spa_py.cp37-win_amd64.exp
Generating code
Finished generating code
```

ok?

File: pvlib/spa_c_files/README.md (hunk 1 above)
Comment (mikofski) [reply pvlib/spa_c_files/README.md]: great idea, okay, it now asks for users name, and sends that, if no name, then it fails with some ugly message which contains the contents of spa.c which says something like:
>Name must be atleast 2 valid characters.

Comment (mikofski) [reply pvlib/spa_c_files/README.md]: It looks like the [root `setup.py` checks if the files are present](https://github.com/pvlib/pvlib-python/blob/master/setup.py#L87-L96) so I think it will run okay.

It looks like the CI's had no problems building it either.

Also I just checked it on my PC, and it also works as expected:
* if no `spa.c` or `spa.h` then you get this:
    >WARNING: spa_c files not detected. See installation instructions for more information.
* if yes `spa.c` or `spa.h` then it builds the extension.

**Comment by cwhanse** [comment]
I'm not comfortable with the auto-download, I would be more comfortable with if we sought and received NREL's agreement that the auto-download satisfies their request for registration.  I don't think we should merge until we have their approval. I suspect they will not be pleased with the `pvlib-python` user name and will want individuals and organizations. 

I'd be happy to contact NREL about this.

I appreciate and agree with the motivation to make the build convenient for users, especially with the `timezone` vs. `time_zone` behavior.

**Comment by mikofski** [comment]
@cwhanse sounds good , FYI: I changed it so the user has to enter there name now

**Comment by wholmgren** [comment]
Thanks @mikofski. Can we do something similar for all of the fields?

```python
print('Enter the following to accept the NREL LICENSE:')
VALUES['name'] = input('Name: ')
VALUES['country'] = input('Country: ')
VALUES['company'] = input('Company: ')
VALUES['software'] = input('Software (enter pvlib-python if not bundling with another application): ')
```

**Comment by mikofski** [comment]
@wholmgren [I responded](#discussion_r217212793) to some of your comments that are hidden as outdata above I guess you saw them?

**Comment by wholmgren** [comment]
@mikofski confused about your comment above about the CI building it -- I don't think it is. 

In any case, it didn't work for me:

```
$ cd pvlib/spa_c_files
$ python setup.py build_ext --inplace
$ cd ..
$ cd ..
$ pip install -e .
$ pytest pvlib/test/test_solarposition.py
============================================================================================================ test session starts =============================================================================================================
platform darwin -- Python 3.6.5, pytest-3.6.3, py-1.5.4, pluggy-0.6.0
rootdir: /Users/holmgren/git_repos/pvlib-python, inifile:
plugins: xdist-1.22.2, mock-1.10.0, forked-0.2, cov-2.6.0
collected 30 items

pvlib/test/test_solarposition.py FF...................x........                                                                                                                                                                        [100%]

================================================================================================================== FAILURES ==================================================================================================================
____________________________________________________________________________________________________________ test_spa_c_physical _____________________________________________________________________________________________________________

expected_solpos =                       elevation  apparent_zenith     azimuth  apparent_elevation
2003-10-17T12:30:30Z  39.872046        50.111622  194.340241           39.888378

    @requires_spa_c
    def test_spa_c_physical(expected_solpos):
        times = pd.date_range(datetime.datetime(2003,10,17,12,30,30),
                              periods=1, freq='D', tz=golden_mst.tz)
        ephem_data = solarposition.spa_c(times, golden_mst.latitude,
                                         golden_mst.longitude,
                                         pressure=82000,
>                                        temperature=11)

pvlib/test/test_solarposition.py:59:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pvlib/solarposition.py:203: in spa_c
    delta_t=delta_t
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   TypeError: spa_calc() takes at least 13 positional arguments (6 given)

spa_py.pyx:3: TypeError
__________________________________________________________________________________________________________ test_spa_c_physical_dst ___________________________________________________________________________________________________________

expected_solpos =                       elevation  apparent_zenith     azimuth  apparent_elevation
2003-10-17T12:30:30Z  39.872046        50.111622  194.340241           39.888378

    @requires_spa_c
    def test_spa_c_physical_dst(expected_solpos):
        times = pd.date_range(datetime.datetime(2003,10,17,13,30,30),
                              periods=1, freq='D', tz=golden.tz)
        ephem_data = solarposition.spa_c(times, golden.latitude,
                                         golden.longitude,
                                         pressure=82000,
>                                        temperature=11)

pvlib/test/test_solarposition.py:71:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pvlib/solarposition.py:203: in spa_c
    delta_t=delta_t
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   TypeError: spa_calc() takes at least 13 positional arguments (6 given)

spa_py.pyx:3: TypeError
```

**Comment by mikofski** [comment]
>confused about your comment above about the CI building it -- I don't think it is.

no I didn't mean it's building the spa-c files, I meant it is building pvlib-python _without_ the spa-c files, which I think is what we would expect, right? and it is consistently building pvlib-python everytime AFAICT

>In any case, it didn't work for me:

weird, same for me on linux, but seems to work on windows? is this a red herring? grrrrr

**Comment by wholmgren** [comment]
@cwhanse @mikofski I support asking NREL if the latest interface meets their requirements. Here's what it looked like after I pulled @mikofski's latest changes that require the user to enter all information:

```
$ python setup.py build_ext --inplace
# NOTICE

Copyright (c) 2008-2011 Alliance for Sustainable Energy, LLC, All Rights Reserved

The Solar Position Algorithm ("Software") is code in development prepared by
employees of the Alliance for Sustainable Energy, LLC, (hereinafter the
"Contractor"), under Contract No. DE-AC36-08GO28308 ("Contract") with the
U.S. Department of Energy (the "DOE"). The United States Government has been
granted for itself and others acting on its behalf a paid-up, non-exclusive,
irrevocable, worldwide license in the Software to reproduce, prepare
derivative works, and perform publicly and display publicly. Beginning five
(5) years after the date permission to assert copyright is obtained from the
DOE, and subject to any subsequent five (5) year renewals, the United States
Government is granted for itself and others acting on its behalf a paid-up,
non-exclusive, irrevocable, worldwide license in the Software to reproduce,
prepare derivative works, distribute copies to the public, perform publicly
and display publicly, and to permit others to do so. If the Contractor ceases
to make this computer software available, it may be obtained from DOE's
Office of Scientific and Technical Information's Energy Science and
Technology Software Center (ESTSC) at P.O. Box 1020, Oak Ridge, TN
37831-1020. THIS SOFTWARE IS PROVIDED BY THE CONTRACTOR "AS IS" AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE CONTRACTOR OR THE U.S. GOVERNMENT BE LIABLE
FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER,
INCLUDING BUT NOT LIMITED TO CLAIMS ASSOCIATED WITH THE LOSS OF DATA OR
PROFITS, WHICH MAY RESULT FROM AN ACTION IN CONTRACT, NEGLIGENCE OR OTHER
TORTIOUS CLAIM THAT ARISES OUT OF OR IN CONNECTION WITH THE ACCESS, USE OR
PERFORMANCE OF THIS SOFTWARE.

The Software is being provided for internal, noncommercial purposes only and
shall not be re-distributed. Please contact [Jean
Schulte](mailto:Jean.Schulte@nrel.gov) in the NREL Commercialization and
Technology Transfer Office for information concerning a commercial license to
use the Software.

As a condition of using the Software in an application, the developer of the
application agrees to reference the use of the Software and make this Notice
readily accessible to any end-user in a Help|About screen or equivalent manner.


Enter the following information to accept the NREL LICENSE ...

Name: Will Holmgren
Company (or enter "Individual"): University of Arizona
Country: USA
Email (optional): holmgren@email.arizona.edu
running build_ext
building 'spa_py' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/holmgren/miniconda3/envs/pvlibfx36/include -arch x86_64 -I/Users/holmgren/miniconda3/envs/pvlibfx36/include -arch x86_64 -I/Users/holmgren/git_repos/pvlib-python/pvlib/spa_c_files -I/Users/holmgren/miniconda3/envs/pvlibfx36/include/python3.6m -c spa_py.c -o build/temp.macosx-10.9-x86_64-3.6/spa_py.o
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/holmgren/miniconda3/envs/pvlibfx36/include -arch x86_64 -I/Users/holmgren/miniconda3/envs/pvlibfx36/include -arch x86_64 -I/Users/holmgren/git_repos/pvlib-python/pvlib/spa_c_files -I/Users/holmgren/miniconda3/envs/pvlibfx36/include/python3.6m -c spa.c -o build/temp.macosx-10.9-x86_64-3.6/spa.o
gcc -bundle -undefined dynamic_lookup -Wl,-rpath,/Users/holmgren/miniconda3/envs/pvlibfx36/lib -L/Users/holmgren/miniconda3/envs/pvlibfx36/lib -headerpad_max_install_names -Wl,-rpath,/Users/holmgren/miniconda3/envs/pvlibfx36/lib -L/Users/holmgren/miniconda3/envs/pvlibfx36/lib -headerpad_max_install_names -arch x86_64 build/temp.macosx-10.9-x86_64-3.6/spa_py.o build/temp.macosx-10.9-x86_64-3.6/spa.o -L/Users/holmgren/miniconda3/envs/pvlibfx36/lib -o /Users/holmgren/git_repos/pvlib-python/pvlib/spa_c_files/spa_py.cpython-36m-darwin.so
```

**Comment by wholmgren** [comment]
> no I didn't mean it's building the spa-c files, I meant it is building pvlib-python without the spa-c files, which I think is what we would expect, right? and it is consistently building pvlib-python everytime AFAICT

Great. Let's not add this to the CI.

No clue about the platform/test issues. Sorry.

**Comment by mikofski** [comment]
>No clue about the platform/test issues. Sorry.

It's "time_zone" now, not "timezone"!

pdb to the rescue!

File: pvlib/spa_c_files/setup.py [hunk 3]
```diff
@@ -1,9 +1,41 @@
...
+VALUES['company'] = input('Company (or enter "Individual"): ')
+VALUES['country'] = input('Country: ')
+VALUES['email'] = input('Email (optional): ')
+DATA = parse.urlencode(VALUES).encode('ascii')
+
+# get spa.c
+REQ = request.Request(SPA_C_URL, DATA)
+with request.urlopen(REQ) as response:
+    SPA_C = response.read()
+SPA_C = SPA_C.replace(b'timezone', b'time_zone')
```
Comment (wholmgren) [inline pvlib/spa_c_files/setup.py]: you might consider a comment here about why you're doing this and also reference the github issue.

**Comment by mikofski** [comment]
OK, works now in linux too, thanks for catching that! I reverted the Python API in `pvlib.solarposition.spa_c` to continue to use `timezone` without the underscore, so it's only the cython version in `pvlib.spa_c_files.spa_py.spa_calc` that confusingly takes a `timezone` but outputs a `time_zone`, sorry!

**Comment by mikofski** [comment]
See this explanation from the [cython users google group](https://groups.google.com/forum/#!topic/cython-users/pjbhYrpl_rU) - evidently , only a windows issue, and only since Python-3.5, `pyconfig.h` redefines timezone as a function.

**Comment by mikofski** [comment]
I should probably leave, so I slightly revert the changes, and added spa_py.c back in after accidently deleting it, you might have you check your tests again, but make sure to purge your build folders, I had to on linux, it passes for me. I just thought it was better to have a consistent in/out api for spa_calc, even tho timezone isn't used that much.

**Comment by wholmgren** [comment]
This seems sub-optimal but not a must fix:

```
$ python setup.py build_ext --inplace
$ git diff
diff --git a/pvlib/spa_c_files/spa_py.c b/pvlib/spa_c_files/spa_py.c
index 378c34c..b711b0d 100644
--- a/pvlib/spa_c_files/spa_py.c
+++ b/pvlib/spa_c_files/spa_py.c
@@ -4,10 +4,10 @@
 {
     "distutils": {
         "depends": [
-            "spa.h"
+            "/Users/holmgren/git_repos/pvlib-python/pvlib/spa_c_files/spa.h"
         ],
         "include_dirs": [
-            "."
+            "/Users/holmgren/git_repos/pvlib-python/pvlib/spa_c_files"
         ],
         "name": "spa_py",
         "sources": [
```

**Comment by mikofski** [comment]
I'm not a fan either, if rather drop the generated Cython, I can't think of a case where any user would use it

**Comment by mikofski** [comment]
I think that's only showing up on your machine after you build on place and replace that `spa_py.c` file locally. It doesn't look that way on GitHub https://github.com/mikofski/pvlib-python/blob/fix_spa_c_files_timezone_compile_fail/pvlib/spa_c_files/spa_py.c

**Comment by wholmgren** [comment]
My objection is when I build the package it modifies a file that git tracks, so now I have a file that shows up under "not staged for commit" in my local repo. If I used this regularly it would be a problem for me because I use ``git commit -a`` all the time. But I don't, so I won't be a stickler about it. Maybe there is some difference between your platform and mine or maybe I'm not doing something right. In any case, if we're going to require cython to use ``spa_c`` then we could ``git rm spa_py.c`` as you suggested earlier and also add it to ``.gitignore`` and problem solved.

**Comment by mikofski** [comment]
Sorry, I misunderstood, yes the same annoying thing happens to me too. I vote to git remove it and then git ignore as you suggest.

**Comment by wholmgren** [comment]
What do you think of the LGTM alerts? No big deal for this?

**Comment by mikofski** [comment]
>What do you think of the LGTM alerts? No big deal for this?

I thought about this, it's only a concern for Python-2, b/c in Python-3, `input` is always coerced to string, but in Python-2, it calls evil `eval`. But I think in this case it's okay, because:
1. the user probably should not try to build the spa-c files in Python-2. I don't know if the byte-strings will work without some compatibility fixes, and I don't have the patience for something that affects 1% of users
2. the user is using `input` on themselves, so if they happen to be using Python-2.7, and it magically works, and they happen to type `rm -rf /` as their name, then it's kind of their own fault

**Comment by cwhanse** [comment]
@mikofski @wholmgren am trading emails with NREL will let you know if/when they approve.

**Comment by mikofski** [comment]
OK, I agree, I'll factor out the download code.

And by the way, it works fine in Python-2

**Comment by cwhanse** [comment]
I agree with the factoring at this point.

**Comment by mikofski** [comment]
BTW: refactoring out the autodownload removes the `input` threat, which turns out it was real, b/c the `setup.py` byte-string patching _does_ work on py2

Anyway, OK now?

**Comment by mikofski** [comment]
Here's the old code for posterity:

```python
from urllib import request, parse

SPA_C_URL = r'https://midcdmz.nrel.gov/apps/download.pl'
SPA_H_URL = r'https://midcdmz.nrel.gov/spa/spa.h'
VALUES = {'software': 'SPA'}
LICENSE = 'SPA_NOTICE.md'

with open(os.path.join(DIRNAME, LICENSE)) as f:
    print(f.read())

print('\nEnter the following information to accept the NREL LICENSE ...\n')
VALUES['name'] = input('Name: ')
VALUES['company'] = input('Company (or enter "Individual"): ')
VALUES['country'] = input('Country: ')
VALUES['email'] = input('Email (optional): ')
DATA = parse.urlencode(VALUES).encode('ascii')

# get spa.c
REQ = request.Request(SPA_C_URL, DATA)
with request.urlopen(REQ) as response:
    SPA_C = response.read()
# patch here ...

# get spa.h
with request.urlopen(SPA_H_URL) as response:
    SPA_H = response.read()
# patch here ...
```

File: pvlib/solarposition.py [hunk 4]
```diff
@@ -194,7 +194,7 @@ def spa_c(time, latitude, longitude, pressure=101325, altitude=0,
                                 hour=date.hour,
                                 minute=date.minute,
                                 second=date.second,
-                                timezone=0,  # date uses utc time
+                                time_zone=0,  # date uses utc time
```
Comment (cwhanse) [inline pvlib/solarposition.py]: Add a comment above, just below the link to the spa code, that explains that `timezone` is replaced with `time_zone` in `spa.c` during the `pvlib` build process.

File: pvlib/solarposition.py [hunk 5]
```diff
@@ -206,7 +206,7 @@ def spa_c(time, latitude, longitude, pressure=101325, altitude=0,
     spa_df = pd.DataFrame(spa_out, index=time)
 
     if raw_spa_output:
-        return spa_df
+        return spa_df.rename(columns={'time_zone': 'timezone'})
```
Comment (cwhanse) [inline pvlib/solarposition.py]: Add a comment explaining why this is done

File: pvlib/spa_c_files/README.md [hunk 6]
```diff
@@ -1,34 +1,80 @@
...
-[Reda, I.; Andreas, A. (2003). Solar Position Algorithm for Solar Radiation Applications. 55 pp.; NREL Report No. TP-560-34302](
-http://www.nrel.gov/docs/fy08osti/34302.pdf).
+NREL provides a C implementation of the solar position algorithm described in
+[Reda, I.; Andreas, A. (2003). Solar Position Algorithm for Solar Radiation Applications. 55 pp.; NREL Report No. TP-560-34302](http://www.nrel.gov/docs/fy08osti/34302.pdf).
 
-This folder contains the files required to make NREL's C code accessible
-to the ``pvlib-python`` package. We use the Cython package to wrap NREL's SPA 
+This folder contains the files required to make SPA C code accessible
+to the `pvlib-python` package. We use the Cython package to wrap the NREL SPA 
 implementation.
```
Comment (cwhanse) [inline pvlib/spa_c_files/README.md]: Copy the comment from `solarposition.py` that explains that we replace `timezone` with `time_zone` at build

File: pvlib/spa_c_files/setup.py [hunk 7]
```diff
@@ -1,9 +1,34 @@
...
 from distutils.core import setup
 from distutils.extension import Extension
 from Cython.Build import cythonize
 
+DIRNAME = os.path.dirname(__file__)
+
+# patch spa.c
+with open(os.path.join(DIRNAME, 'spa.c'), 'rb') as f:
+    SPA_C = f.read()
+# replace timezone with time_zone to avoid a nameclash the function
```
Comment (cwhanse) [inline pvlib/spa_c_files/setup.py]: with the function

**Comment by cwhanse** [comment]
Ready to go, I think a few inline comments would be wise to remind us why we change `timezone`

File: pvlib/spa_c_files/README.md (hunk 6 above)
Comment (mikofski) [reply pvlib/spa_c_files/README.md]: There is already a comment in this readme on line 17-18:
>The SPA C files will be patched to avoid
[Python bug 24643](https://bugs.python.org/issue24643) when the extension is
built.

Should I add more detail than what's already in `setup.py`?

Comment (cwhanse) [reply pvlib/spa_c_files/README.md]: It would help, I think.  What a user (or code maintainer sees) is the change in keyword, which isn't easily linked to the Python bug unless someone already knows what bug 24643 is.  Just thinking down the road to when the bug is fixed and we can revert this patch, or when someone asks why we are editing spa.c.

File: pvlib/solarposition.py (hunk 4 above)
Comment (mikofski) [reply pvlib/solarposition.py]: added [this note](../../../mikofski/pvlib-python/blob/fix_spa_c_files_timezone_compile_fail/pvlib/solarposition.py#L165-L167)
>Note: The ``timezone`` field in the SPA C files is replaced with ``time_zone`` to avoid a nameclash with the function ``__timezone`` that is redefined by Python-3.5. This issue is `Python bug 24643 <https://bugs.python.org/issue24643>`_.

File: pvlib/spa_c_files/README.md (hunk 6 above)
Comment (mikofski) [reply pvlib/spa_c_files/README.md]: ok

**Comment by wholmgren** [comment]
Thanks @mikofski and @cwhanse. I think the additional comments will helpful.

**Comment by mikofski** [comment]
@wholmgren AFAIK I think this is ready whenever, just waiting for approval from @cwhanse

**Comment by cwhanse** [comment]
Closes #168
